name: Build and Deploy

# Se ejecuta en push a la rama 'main'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Ejecutar el build de Vite
      - name: Build project
        run: npm run build

      # Desplegar en el servidor FTP
      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /public_html
